# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
addons:
  apt:
    update: true
    packages:
      - wget
      - gfortran
      - openmpi-bin
before_script:
  - # Install p4est 2.2 from sources
  - PACKAGE=p4est
  - VERSION=2.2
  - INSTALL_ROOT=/opt
  - P4EST_INSTALL=$INSTALL_ROOT/$PACKAGE/$VERSION
  - TAR_FILE=$PACKAGE-$VERSION.tar.gz
  - URL="https://github.com/p4est/p4est.github.io/raw/master/release"
  - ROOT_DIR=/tmp
  - SOURCES_DIR=$ROOT_DIR/$PACKAGE-$VERSION
  - BUILD_DIR=$SOURCES_DIR/build
  - wget -q $URL/$TAR_FILE -O $ROOT_DIR/$TAR_FILE
  - mkdir -p $SOURCES_DIR
  - tar xzf $ROOT_DIR/$TAR_FILE -C $SOURCES_DIR --strip-components=1
  - cd $SOURCES_DIR
  - ./configure --prefix=$P4EST_INSTALL --without-blas --without-lapack --enable-mpi
  - make --quiet
  - make --quiet install
  - rm -rf $ROOT_DIR/$TAR_FILE $SOURCES_DIR
  - export P4EST_ROOT_DIR=$P4EST_INSTALL
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.1
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
